# baseURL: "https://luoxding.github.io/"
baseURL: /
title: Laoluo's Blog
paginate: 10
theme: PaperMod
languageCode: zh
# defaultContentLanguage: zh

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: true
buildExpired: false
enableEmoji: true
# googleAnalytics: G-P9B4DKL1HC

minify:
  disableXML: true
  minifyOutput: true

menu:
  main:
    # - name: "ç³»åˆ—"
    #   url: "/series/" # å‡è®¾"ç³»åˆ—"æ˜¯ä¸€ä¸ªåŒ…å«å¤šä¸ªç›¸å…³æ–‡ç« çš„éƒ¨åˆ†
    #   weight: 3
    #   identifier: "series" # è¿™æ˜¯ä¸€ä¸ªå¯é€‰çš„å”¯ä¸€æ ‡è¯†ç¬¦ï¼Œç”¨äºå†…éƒ¨å¯¼èˆªå’Œé¡µé¢å¼•ç”¨
    # - name: "æ•™ç¨‹"
    #   url: "/tutorials/" # æŒ‡å‘"ç³»åˆ—"ä¸‹çš„ä¸€ä¸ªå­ç³»åˆ—é¡µé¢æˆ–éƒ¨åˆ†
    #   weight: 4
    #   parent: "series"
    # - name: "ç”Ÿæ´»"
    #   url: "/life/" # å¦ä¸€ä¸ªå­ç³»åˆ—é¡µé¢æˆ–éƒ¨åˆ†
    #   weight: 5
    #   parent: "series"
    - name: å½’æ¡£
      url: archives
      weight: 10
    - name: åˆ†ç±»
      url: categories/
      weight: 20
    - name: æ ‡ç­¾
      url: tags/
      weight: 30
    - name: å…³äº
      url: about/
      weight: 9
    - name: ğŸ”
      url: search/
      weight: 99
    # - name: ç®€å†
    #   url: /resume/
      # weight: 60
    - name: é“¾æ¥
      url: /links/
      weight: 70
    - name: é€ŸæŸ¥
      url: manual/
      weight: 31
    # - name: å¤–é“¾
    #   url: https://github.com/tobyscott25
    #   weight: 90


outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "ä¸ªäººç¬”è®°éšç¬”å°ç«™"
  author: James
  # author: ["Me", "You"] # multiple authors
  # images: /favicon.ico

  defaultTheme: auto
  disableThemeToggle: false
  # ShowShareButtons: true
  # ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowToc: true
  TocOpen: true # è‡ªåŠ¨å±•å¼€ç›®å½•
  # home-info mode
  homeInfoParams:
    Title: "Hi there ğŸ‘‹ Hey, Iâ€™m Joel \U0001F44B"
    Content: >
      - âœ¨ æ¬¢è¿æ¥åˆ°æˆ‘çš„ä¸ªäººåšå®¢

      - ğŸ”­ è¿™é‡Œè®°å½•æˆ‘å…³äºå­¦ä¹ ç”Ÿæ´»ä»¥åŠå·¥ä½œç­‰ç¬”è®°

  socialIcons:
    - name: github
      url: "https://github.com/luoxding/"
    # - name: leetcode
    #   url: "https://leetcode.cn/u/fzzf-z/"
    # - name: rss
    #   url: "index.xml"
  # StartYear: 2020 # åº•éƒ¨å¼€å§‹å¹´ä»½
  # FilingNo: å¡«å†™è‡ªå·±çš„å¤‡æ¡ˆå· # åº•éƒ¨å¤‡æ¡ˆå·

  assets:
    favicon: "/icons/linux.png"
  hideFooter: true
  FilingNo: "" # åº•éƒ¨å¤‡æ¡ˆå·
  # FilingNo: "é»”ICPå¤‡2022001597å·" # åº•éƒ¨å¤‡æ¡ˆå·

markup:
  goldmark:
    renderer:
      unsafe: true

permalinks:
  posts: /:slug

# enable toc on every post page, default false
# ShowToc: true